# Generated by Django 5.2.6 on 2025-09-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('seeker', 'Seeker')], default='seeker', max_length=10),
        ),
    ]
