# Generated by Django 5.2.6 on 2025-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
