# Generated by Django 5.2.6 on 2025-09-27 15:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=accounts.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
