# Generated by Django 5.2.6 on 2025-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_urls',
        ),
    ]
