# Generated by Django 5.2.6 on 2025-09-27 15:49

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='id',
            field=models.CharField(default=notifications.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=notifications.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
