# Generated by Django 5.2.6 on 2025-09-27 15:49

import message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.CharField(default=message.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=message.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
