# Generated by Django 5.2.6 on 2025-09-25 21:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1BHK', '1 BHK Apartment'), ('2BHK', '2 BHK Apartment'), ('3BHK', '3 BHK Apartment'), ('4BHK', '4+ BHK Apartment'), ('Studio', 'Studio Apartment'), ('SingleRoom', 'Single Room'), ('DoubleRoom', 'Double Room'), ('TripleRoom', 'Triple Room'), ('PG_Single', 'PG - Single Room'), ('PG_Double', 'PG - Double Sharing'), ('PG_Triple', 'PG - Triple Sharing'), ('PG_Quad', 'PG - 4+ Sharing'), ('House', 'Independent House'), ('Villa', 'Villa'), ('Cottage', 'Cottage House'), ('Office', 'Office Space'), ('Shop', 'Commercial Shop'), ('Warehouse', 'Warehouse'), ('Land', 'Plot/Land'), ('Other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Room'), ('pg', 'PG'), ('house', 'House'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('commercial', 'Commercial'), ('land', 'Land'), ('other', 'Other')], max_length=20)),
                ('roomConfig', models.CharField(blank=True, choices=[('1bed', '1 Bedroom'), ('2bed', '2 Bedrooms'), ('3bed', '3 Bedrooms'), ('4bed', '4+ Bedrooms'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4+ BHK'), ('single', 'Single Occupancy'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing'), ('quad', '4+ Sharing'), ('studio', 'Studio')], max_length=20)),
                ('listingType', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deposit', models.CharField(blank=True, max_length=100)),
                ('minimumPrice', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximumPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('areaSize', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(choices=[('Available', 'Available Now'), ('Occupied', 'Currently Occupied'), ('Maintenance', 'Under Maintenance'), ('Coming_Soon', 'Available Soon')], default='Available', max_length=20)),
                ('furnishingStatus', models.CharField(choices=[('Fully', 'Fully Furnished'), ('Semi', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=20)),
                ('genderPreference', models.CharField(choices=[('Male', 'Male Only'), ('Female', 'Female Only'), ('Unisex', 'Both Male & Female'), ('Any', 'No Preference')], default='Any', max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('imageIds', models.JSONField(blank=True, default=list)),
                ('availableFrom', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-createdAt'],
            },
        ),
    ]
