# Generated by Django 5.2.6 on 2025-09-27 15:49

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.CharField(default=properties.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(default=properties.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='id',
            field=models.CharField(default=properties.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
