# Generated by Django 5.2.6 on 2025-09-27 15:49

import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='id',
            field=models.CharField(default=support.models.generate_unique_id, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
